site_name: ORM::Factory
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - DSL design: dsl-design.md
  - Build strategies: build-strategies.md
  - Sequences: sequences.md
  - Transient attributes: transient.md
  - Inheritance: inheritance.md
  - Persistence: persistence.md
  - Tests: tests.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      linenums: true
