site_name: ORM::Factory
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - DSL design: dsl-design.md
  - Build strategies: build-strategies.md
  - Strategies: strategy.md
  - Collections: collections.md
  - Overrides: overrides.md
  - Dependent attributes: dependent-attrs.md
  - Aliases: aliases.md
  - Class resolution: class-resolution.md
  - Sequences: sequences.md
  - Transient attributes: transient.md
  - Inheritance: inheritance.md
  - Variants: variants.md
  - Associations: associations.md
  - Callbacks: callbacks.md
  - Persistence: persistence.md
  - Construction: construction.md
  - Tests: tests.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      linenums: true
